/**
 * CrashAvoidanceSystem
 * This is a CAS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * InfrastructureApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_InfrastructureApi_H_
#define IO_SWAGGER_CLIENT_API_InfrastructureApi_H_


#include "../ApiClient.h"

#include "Rule.h"

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  InfrastructureApi
{
public:
    InfrastructureApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~InfrastructureApi();
    /// <summary>
    /// Update the current rule for an intersection in the system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="intersectionId">The id of the intersection for which the current rule is changed</param>
    /// <param name="body">The rule that should be used in the given intersection</param>
    pplx::task<void> changeCurrentRule(
        int64_t intersectionId,
        std::shared_ptr<Rule> body
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_InfrastructureApi_H_ */

