/**
 * CrashAvoidanceSystem
 * This is a CAS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * VehicleApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_VehicleApi_H_
#define IO_SWAGGER_CLIENT_API_VehicleApi_H_


#include "../ApiClient.h"

#include "Vehicle.h"
#include "VehicleData.h"
#include <cpprest/details/basic_types.h>

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  VehicleApi
{
public:
    VehicleApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~VehicleApi();
    /// <summary>
    /// Find vehicle by vin
    /// </summary>
    /// <remarks>
    /// Returns a single vehicle
    /// </remarks>
    /// <param name="vin">Vehicle identification number of the vehicle whose data to return</param>
    pplx::task<std::shared_ptr<Vehicle>> getVehicle(
        utility::string_t vin
    );
    /// <summary>
    /// Register new vehicle to the system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="body">Information uniquely identifying a vehicle</param>
    pplx::task<void> newVehicle(
        std::shared_ptr<Vehicle> body
    );
    /// <summary>
    /// Update vehicle data by vin
    /// </summary>
    /// <remarks>
    /// Updates data for one vehicle
    /// </remarks>
    /// <param name="vin">Vehicle identification number of the vehicle whose data to update</param>
    /// <param name="body">Vehicle data object that contains the latest information about the car</param>
    pplx::task<void> newVehicleData(
        utility::string_t vin,
        std::shared_ptr<VehicleData> body
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_VehicleApi_H_ */

