/**
 * CrashAvoidanceSystem
 * This is a CAS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Rule.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Rule_H_
#define IO_SWAGGER_CLIENT_MODEL_Rule_H_


#include "../ModelBase.h"

#include "RuleEntry.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Rule
    : public ModelBase
{
public:
    Rule();
    virtual ~Rule();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Rule members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<RuleEntry>>& getEntries();
    bool entriesIsSet() const;
    void unsetEntries();
    void setEntries(std::vector<std::shared_ptr<RuleEntry>> value);

protected:
    std::vector<std::shared_ptr<RuleEntry>> m_Entries;
    bool m_EntriesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Rule_H_ */
