/**
 * CrashAvoidanceSystem
 * This is a CAS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Vehicle.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Vehicle_H_
#define IO_SWAGGER_CLIENT_MODEL_Vehicle_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Vehicle
    : public ModelBase
{
public:
    Vehicle();
    virtual ~Vehicle();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Vehicle members

    /// <summary>
    /// The unique vehicle identification number
    /// </summary>
    utility::string_t getVin() const;
        void setVin(utility::string_t value);
    /// <summary>
    /// The address at which the Vehicle receives alers and information
    /// </summary>
    utility::string_t getServiceAddress() const;
    bool serviceAddressIsSet() const;
    void unsetServiceAddress();
    void setServiceAddress(utility::string_t value);

protected:
    utility::string_t m_Vin;
        utility::string_t m_ServiceAddress;
    bool m_ServiceAddressIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Vehicle_H_ */
