/**
 * CrashAvoidanceSystem
 * This is a CAS server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * VehicleData.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_VehicleData_H_
#define IO_SWAGGER_CLIENT_MODEL_VehicleData_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Position.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  VehicleData
    : public ModelBase
{
public:
    VehicleData();
    virtual ~VehicleData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VehicleData members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Position> getPosition() const;
        void setPosition(std::shared_ptr<Position> value);
    /// <summary>
    /// 
    /// </summary>
    int64_t getSpeed() const;
    bool speedIsSet() const;
    void unsetSpeed();
    void setSpeed(int64_t value);
    /// <summary>
    /// Direction in which the vehicle goes
    /// </summary>
    utility::string_t getDirection() const;
    bool directionIsSet() const;
    void unsetDirection();
    void setDirection(utility::string_t value);

protected:
    std::shared_ptr<Position> m_Position;
        int64_t m_Speed;
    bool m_SpeedIsSet;
    utility::string_t m_Direction;
    bool m_DirectionIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_VehicleData_H_ */
